from enum import Enum

class TipoAcomodacoes(Enum):
  CAMA_CASAL = 'CAMA_CASAL'
  CAMAS_CASAL_SOLTEIRO = 'CAMAS_CASAL_SOLTEIRO'
  CAMAS_SOLTEIRO = 'CAMAS_SOLTEIRO'
  CAMAS_CASAL_BELICHE = 'CAMAS_CASAL_BELICHE'