from enum import Enum

class TipoQuarto(Enum):
  STANDARD_NAO_FUMANTES = 'STANDARD_NAO_FUMANTES'
  STANDARD_FUMANTES = 'STANDARD_FUMANTES'
  VIP_NAO_FUMANTES = 'VIP_NAO_FUMANTES'
  VIP_FUMANTES = 'VIP_FUMANTES'